# This file was generated by GoReleaser. DO NOT EDIT.
cask "vybava" do
  version "0.65.0"

  on_macos do
    on_arm do
      sha256 "6101d68fe414a13630586aba9cb15348d395a1deb113f4c546f66c76b9de4bf1"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ddde5e2f4d5fe7410b542b49d822ac77657e5be330335032c582d0ca37f21cf"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9faec1aff98f88794344fb10636f34ff18efea3e4ab209d0d997f5d228811bbd"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc6631a214c696a5d34383cb23c2ebea9ace82300e2e30d5b8c033ecb0b1e2cf"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vybava"
  desc "Portable engineering tools, agent skills, and diagnostics for every project"
  homepage "https://github.com/henderson-tech/vybava"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vybava"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vybava"]
    end
  end

  # No zap stanza required
end
