# This file was generated by GoReleaser. DO NOT EDIT.
cask "vybava" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "97eb671f5cf59ed2935cb0e7db1bd16a3fe36c0b5445c9ec3a9c903cd289ec04"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a4e2662f63f6c4f65725b7070c63c4237d122fc22413e8093fafcbfa941acba1"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "677a2893ea69e1087e0c0598eaa8ab5fa169e21ef47abfb89dda1783f0fb7bb5"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b037bc4ec2de910ea3898aa1c0f60b50a51965d3392d0548b0764642e91b77b"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vybava"
  desc "Portable engineering tools, agent skills, and diagnostics for every project"
  homepage "https://github.com/henderson-tech/vybava"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vybava"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vybava"]
    end
  end

  # No zap stanza required
end
