# This file was generated by GoReleaser. DO NOT EDIT.
cask "vybava" do
  version "0.57.0"

  on_macos do
    on_arm do
      sha256 "b1c74ff2d3cc450876642d9af52cb45fa87d8edf3b76163d600bcc1d2cb61731"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cd1c43731008aa98e2b42ed3cbc772f71f4a6ea59a02f796d371ec2c8af58c38"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3316436085609ccf5b6e7d30d9ba9d7937f9b12abd55f166333d2810b91bc21d"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ade585c763a8fe92be63f92b8eccefe2cd6108aabafbb428d11df0a7adb87ca"
      url "https://github.com/henderson-tech/vybava/releases/download/v#{version}/vybava_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vybava"
  desc "Portable engineering tools, agent skills, and diagnostics for every project"
  homepage "https://github.com/henderson-tech/vybava"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vybava"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vybava"]
    end
  end

  # No zap stanza required
end
